package xyz.enkdev.sessionpass

import java.nio.charset.StandardCharsets

/**
 * Provides mechanisms to request and compare One-Time-Session-Verification (OTSV) Codes received by a webserver.
 */
class OtsvCode {
    /**
     * Requests a OTSVCode from the webserver.
     * 
     * @param codeFlag The flag of the length for the code. 0 = Small, 1 = Medium, 2 = Large
     * 
     * @return A new OTSVCode generated by the webserver.
     */
    fun requestOtsvCode(codeFlag: Int): String? {
        val res = HttpHelper.httpPost("https://enkdev.xyz/cdn/php/sessionpass/generateOtsvCode.php", mapOf("cf" to 
                codeFlag.toString()))
        
        return res?.toString(StandardCharsets.UTF_8)
    }

    /**
     * Compares a received OTSVCode with one that the Webserver holds.
     * To be called after requestOtsvCode has been invoked.
     * 
     * @param otsvCode The OTSVCode received from the webserver
     * @param codeFlag The flag of the length for the code. 0 = Small, 1 = Medium, 2 = Large
     * 
     * @return `true` if the code is correct, `false` if not
     */
    fun compareOtsvCode(otsvCode: String?, codeFlag: Int?): Boolean {
        var isSame = false
        
        if (otsvCode != null && codeFlag != null) {
            val res = HttpHelper.httpPost("https://enkdev.xyz/cdn/php/sessionpass/compareCode.php",
                mapOf("code" to otsvCode, "cf" to codeFlag.toString()))
            
            try {
                val response = res?.toString(StandardCharsets.UTF_8)
                
                if (response == "true") {
                    isSame = true
                }
            } catch (e: Exception) {
                println(e.message)
            }
        } else {
            println("otsvCode is null, can't check.")
        }
        
        return isSame
    }
}