//
// Created by EnKdev on 27.11.2024.
//

#ifndef OTSVCODE_H
#define OTSVCODE_H

#include <string>

namespace EnKdev::SessionPass {
    /**
     * Provides mechanisms to request and compare One-Time-Session-Verification (OTSV) Codes received by a webserver.
     */
    class OtsvCode {
    public:
        /**
         * Requests an OTSVCode from the webserver.
         *
         * @param codeFlag The flag of the length for the code. 0 = Small, 1 = Medium, 2 = Large
         *
         * @return A new OTSVCode generated by the webserver.
         */
        static std::string requestOtsvCode(int codeFlag);

        /**
         * Compares a received OTSVCode with one that the webserver holds.
         * To be called after requestOtsvCode has been invoked.
         *
         * @param otsvCode The OTSVCode recieved from the webserver.
         * @param codeFlag The flag of the length for the code. 0 = Small, 1 = Medium, 2 = Large
         *
         * @return `true` if the code is correct, `false` if not.
         */
        bool compareOtsvCode(const std::string& otsvCode, int codeFlag);
    };
}



#endif //OTSVCODE_H
